[general]
import = ["./dracula.toml"]

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" }, # Option + Right: Move forward one word
  { key = "Left", mods = "Alt", chars = "\u001BB" },  # Option + Left: Move backward one word
]
